/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pc.glb --transform 
Files: public/models/pc.glb [4.05MB] > C:\Users\DELL\3d_portfolio\pc-transformed.glb [267.86KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const PcModel=(props)=> {
  const { nodes, materials } = useGLTF('/pc-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.JS_text001_0.geometry} material={materials.PaletteMaterial001} position={[0, -4.5, -1.5] } rotation={[-0.01, -0.2, -0.1]} />
    </group>
  )
}

export default PcModel;
useGLTF.preload('/pc-transformed.glb')
