/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sphere.glb --transform 
Files: public/models/sphere.glb [5.77MB] > C:\Users\DELL\3d_portfolio\sphere-transformed.glb [593.18KB] (90%)
Author: Rafiozo (https://sketchfab.com/Rafiozo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dyson-sphere-1fa6397201a0428d89b3d9c078727e5f
Title: Dyson Sphere
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sphere-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere001_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={0.518} />
      <mesh geometry={nodes.BezierCircle_Material003_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={0.518} />
      <mesh geometry={nodes.BezierCircle001_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={0.518} />
      <mesh geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={0.518} />
    </group>
  )
}

useGLTF.preload('/sphere-transformed.glb')
